### ISSUE TITLE
404 in github actions

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry-toolchain#11]
This action has been working great for me but suddenly (today) getting 404s:
```
Run foundry-rs/foundry-toolchain@v1
  
Error: Error: Unexpected HTTP response: 404
```

**Comment by hayesgm** [comment]
I am also seeing this error from GitHub Actions pulling the chain.

**Comment by tom2o17** [comment]
Also getting this error.

**Comment by marktoda** [comment]
Ah I think the issue is that the plain `nightly` tag didn't include the release assets yesterday: https://github.com/foundry-rs/foundry/releases/tag/nightly. hopefully fixed with today's release, else maybe this action needs to fetch latest nightly release hash

**Comment by onbjerg** [comment]
This will be fixed with the next nightly. GitHub decided to stop our release workflow before the final step.

**Comment by marktoda** [comment]
ty @onbjerg

**Comment by gigamesh** [comment]
Is it possible to just install the latest instead of nightly? I tried this but am still getting the 404. Same result if I remove the `with` section altogether.

```
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: latest
```

**Comment by hayesgm** [comment]
Could you try pinning to an earlier commit, e.g. two days ago's release?

**Comment by gigamesh** [comment]
@hayesgm `version: nightly-63ed1099a74fded7c3a7182b5a508bd7d16743d3` did the trick. thanks!
